version: 2.1

defaults:
  environment: &environment
    DOCKER_REGISTRY: docker.io
    DOCKER_USER: kelvintaywlcircleci

jobs:
  custom_build_from_machine:
    environment:
      <<: *environment
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      - run:
          name: Build Docker image via Kaniko
          command: |
            # set Docker Hub credentials
            echo $DOCKER_CONFIG_JSON > docker-config.json

            docker run \
              -v "$(pwd)/docker-config.json:/kaniko/.docker/config.json:ro" \
              -v "$(pwd):/workspace" \
              gcr.io/kaniko-project/executor:latest \
              --dockerfile sample/Dockerfile \
              --destination "docker.io/kelvintaywlcircleci/fancy-nginx" \
              --context dir:///workspace

workflows:
  main:
    jobs:
      - custom_build_from_machine
